### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PeterBarczi**
added new link for training material

### CODE REVIEW

**Review by moabukar — APPROVED** [review]
lgtm, thanks!

**Comment by PeterBarczi** [comment]
> lgtm, thanks!

no prob.. :) feel free to merge it

**Comment by moabukar** [comment]
> > lgtm, thanks!
> 
> no prob.. :) feel free to merge it

this one is for you - merge it :)

**Comment by PeterBarczi** [comment]
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

Unfortunately I can not..

**Pull request merged**
